const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');
require('dotenv').config();
const app = express();
app.use(cors()); app.use(express.json());
const pool=mysql.createPool({host:process.env.DB_HOST,port:process.env.DB_PORT,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,connectionLimit:10});
function q(id){return '`'+String(id).replace(/`/g,'')+'`'}
const schemaCache=new Map();
async function columns(table){if(schemaCache.has(table))return schemaCache.get(table);const [rows]=await pool.query('SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[table]);const s=new Set(rows.map(r=>r.COLUMN_NAME));schemaCache.set(table,s);return s}
async function ensureSchema(){
 const stmts=[
 `CREATE TABLE IF NOT EXISTS produtos (id INT AUTO_INCREMENT PRIMARY KEY,sku VARCHAR(80) NULL UNIQUE,nome VARCHAR(180) NOT NULL,tipo VARCHAR(80) NOT NULL DEFAULT 'Material',unidade VARCHAR(20) NOT NULL DEFAULT 'un',marca VARCHAR(120) NULL,modelo VARCHAR(120) NULL,estoque DECIMAL(12,3) NOT NULL DEFAULT 0,estoque_minimo DECIMAL(12,3) NOT NULL DEFAULT 0,preco_custo DECIMAL(12,2) NOT NULL DEFAULT 0,preco_venda DECIMAL(12,2) NOT NULL DEFAULT 0,localizacao VARCHAR(120) NULL,categoria_id INT NULL,fornecedor_id INT NULL,ativo TINYINT(1) NOT NULL DEFAULT 1,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS categorias (id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(150) NOT NULL UNIQUE,descricao TEXT NULL,ativo TINYINT(1) NOT NULL DEFAULT 1,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS fornecedores (id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(180) NOT NULL,cnpj VARCHAR(30) NULL,email VARCHAR(180) NULL,telefone VARCHAR(40) NULL,contato VARCHAR(120) NULL,endereco VARCHAR(255) NULL,cidade VARCHAR(120) NULL,estado VARCHAR(2) NULL,observacao TEXT NULL,ativo TINYINT(1) NOT NULL DEFAULT 1,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS usuarios (id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(180) NOT NULL,email VARCHAR(180) NOT NULL UNIQUE,senha VARCHAR(255) NOT NULL,role VARCHAR(30) NOT NULL DEFAULT 'FUNCIONARIO',ativo TINYINT(1) NOT NULL DEFAULT 1,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
 `CREATE TABLE IF NOT EXISTS movimentacoes (id BIGINT AUTO_INCREMENT PRIMARY KEY,produto_id INT NOT NULL,usuario_id INT NULL,tipo VARCHAR(20) NOT NULL,quantidade DECIMAL(12,3) NOT NULL,estoque_anterior DECIMAL(12,3) NOT NULL DEFAULT 0,estoque_posterior DECIMAL(12,3) NOT NULL DEFAULT 0,fornecedor_id INT NULL,documento VARCHAR(120) NULL,motivo VARCHAR(120) NULL,destino VARCHAR(180) NULL,observacao TEXT NULL,data_movimentacao DATE NULL,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_mov_produto(produto_id),INDEX idx_mov_tipo(tipo),INDEX idx_mov_data(data_movimentacao)) ENGINE=InnoDB`,
 ];
 for(const s of stmts) await pool.query(s);
 const add={
  produtos:[['tipo',"VARCHAR(80) NOT NULL DEFAULT 'Material'"],['unidade',"VARCHAR(20) NOT NULL DEFAULT 'un'"],['categoria_id','INT NULL'],['fornecedor_id','INT NULL'],['ativo','TINYINT(1) NOT NULL DEFAULT 1'],['criado_em',"DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP"]],
  categorias:[['ativo','TINYINT(1) NOT NULL DEFAULT 1'],['criado_em','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']],
  fornecedores:[['cnpj','VARCHAR(30) NULL'],['contato','VARCHAR(120) NULL'],['endereco','VARCHAR(255) NULL'],['cidade','VARCHAR(120) NULL'],['estado','VARCHAR(2) NULL'],['observacao','TEXT NULL'],['ativo','TINYINT(1) NOT NULL DEFAULT 1'],['criado_em','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']],
  usuarios:[['senha',"VARCHAR(255) NOT NULL DEFAULT '1234'"],['role',"VARCHAR(30) NOT NULL DEFAULT 'FUNCIONARIO'"],['ativo','TINYINT(1) NOT NULL DEFAULT 1'],['criado_em','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']],
  movimentacoes:[['fornecedor_id','INT NULL'],['documento','VARCHAR(120) NULL'],['motivo','VARCHAR(120) NULL'],['destino','VARCHAR(180) NULL'],['observacao','TEXT NULL'],['data_movimentacao','DATE NULL'],['criado_em','DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP']]
 };
 for(const [table,defs] of Object.entries(add)){const cols=await columns(table);for(const [name,type] of defs){if(!cols.has(name)){try{await pool.query(`ALTER TABLE ${q(table)} ADD COLUMN ${q(name)} ${type}`);cols.add(name)}catch(e){console.warn(`Não foi possível adicionar ${table}.${name}:`,e.message)}}}}
 // seed admin only if table is empty
 const [cnt]=await pool.query('SELECT COUNT(*) AS total FROM usuarios');
 if(Number(cnt[0].total)===0){await pool.query(`INSERT INTO usuarios (nome,email,senha,role,ativo) VALUES (?,?,?,?,1)`,['Administrador','admin@estoque.local','1234','ADMIN']);}
}
app.get('/',(req,res)=>res.json({message:'API ToolStock funcionando!'}));
app.get('/api/teste-db',async(req,res)=>{try{const [rows]=await pool.query('SELECT 1 AS conectado');res.json({sucesso:true,banco:'MySQL conectado!',resultado:rows[0]})}catch(e){res.status(500).json({sucesso:false,erro:e.message})}});

function productSelect(){return `SELECT p.id,p.sku,p.nome,p.tipo,p.unidade,p.marca,p.modelo,p.estoque,p.estoque_minimo,p.preco_custo,p.preco_venda,p.localizacao,p.ativo,p.categoria_id,p.fornecedor_id,c.nome AS categoria,f.nome AS fornecedor FROM produtos p LEFT JOIN categorias c ON c.id=p.categoria_id LEFT JOIN fornecedores f ON f.id=p.fornecedor_id`}
app.get('/api/produtos',async(req,res)=>{try{const [rows]=await pool.query(productSelect()+' ORDER BY p.id DESC');res.json(rows)}catch(e){res.status(500).json({sucesso:false,erro:'Erro ao buscar produtos.',detalhes:e.message})}});
app.get('/api/produtos/:id',async(req,res)=>{try{const [rows]=await pool.query(productSelect()+' WHERE p.id=?',[req.params.id]);if(!rows.length)return res.status(404).json({erro:'Produto não encontrado.'});res.json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.post('/api/produtos',async(req,res)=>{try{const d=req.body;if(!String(d.nome||'').trim())return res.status(400).json({erro:'O nome do produto é obrigatório.'});let cat=d.categoria_id||null,sup=d.fornecedor_id||null;if(!cat&&d.categoria_nome){const [r]=await pool.query('SELECT id FROM categorias WHERE LOWER(nome)=LOWER(?) LIMIT 1',[d.categoria_nome]);if(r.length)cat=r[0].id;else return res.status(400).json({erro:'Categoria não encontrada. Cadastre a categoria antes do produto.'})}if(!sup&&d.fornecedor_nome){const [r]=await pool.query('SELECT id FROM fornecedores WHERE LOWER(nome)=LOWER(?) AND ativo=1 LIMIT 1',[d.fornecedor_nome]);if(r.length)sup=r[0].id;else return res.status(400).json({erro:'Fornecedor não encontrado. Cadastre o fornecedor antes do produto.'})}const [r]=await pool.query(`INSERT INTO produtos (sku,nome,tipo,unidade,marca,modelo,estoque,estoque_minimo,preco_custo,preco_venda,localizacao,categoria_id,fornecedor_id,ativo) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[d.sku||null,d.nome.trim(),d.tipo||'Material',d.unidade||'un',d.marca||null,d.modelo||null,Number(d.estoque??0),Number(d.estoque_minimo??0),Number(d.preco_custo??0),Number(d.preco_venda??0),d.localizacao||null,cat,sup,d.ativo===false?0:1]);const [rows]=await pool.query(productSelect()+' WHERE p.id=?',[r.insertId]);res.status(201).json({sucesso:true,produto:rows[0]})}catch(e){res.status(500).json({sucesso:false,erro:'Erro ao cadastrar produto.',detalhes:e.message})}});
app.put('/api/produtos/:id',async(req,res)=>{try{const d=req.body;const [exists]=await pool.query('SELECT id FROM produtos WHERE id=?',[req.params.id]);if(!exists.length)return res.status(404).json({erro:'Produto não encontrado.'});let cat=d.categoria_id??null,sup=d.fornecedor_id??null;if(cat===null&&d.categoria_nome){const [r]=await pool.query('SELECT id FROM categorias WHERE LOWER(nome)=LOWER(?) LIMIT 1',[d.categoria_nome]);if(r.length)cat=r[0].id;else return res.status(400).json({erro:'Categoria não encontrada.'})}if(sup===null&&d.fornecedor_nome){const [r]=await pool.query('SELECT id FROM fornecedores WHERE LOWER(nome)=LOWER(?) AND ativo=1 LIMIT 1',[d.fornecedor_nome]);if(r.length)sup=r[0].id;else return res.status(400).json({erro:'Fornecedor não encontrado.'})}await pool.query(`UPDATE produtos SET sku=?,nome=?,tipo=?,unidade=?,marca=?,modelo=?,estoque=?,estoque_minimo=?,preco_custo=?,preco_venda=?,localizacao=?,categoria_id=?,fornecedor_id=?,ativo=? WHERE id=?`,[d.sku||null,d.nome?.trim()||'',d.tipo||'Material',d.unidade||'un',d.marca||null,d.modelo||null,Number(d.estoque??0),Number(d.estoque_minimo??0),Number(d.preco_custo??0),Number(d.preco_venda??0),d.localizacao||null,cat,sup,d.ativo===false?0:1,req.params.id]);const [rows]=await pool.query(productSelect()+' WHERE p.id=?',[req.params.id]);res.json({sucesso:true,produto:rows[0]})}catch(e){res.status(500).json({erro:e.message})}});
app.delete('/api/produtos/:id',async(req,res)=>{try{const [m]=await pool.query('SELECT COUNT(*) AS total FROM movimentacoes WHERE produto_id=?',[req.params.id]);if(Number(m[0].total)>0)return res.status(409).json({erro:'Não é possível excluir um produto que possui movimentações. Inative o produto em vez de excluir.'});const [r]=await pool.query('DELETE FROM produtos WHERE id=?',[req.params.id]);if(!r.affectedRows)return res.status(404).json({erro:'Produto não encontrado.'});res.json({sucesso:true})}catch(e){res.status(500).json({erro:e.message})}});

app.get('/api/categorias',async(req,res)=>{try{const [rows]=await pool.query(`SELECT id,nome AS name,descricao AS description,ativo,criado_em AS createdAt FROM categorias ORDER BY nome`);res.json(rows)}catch(e){res.status(500).json({erro:e.message})}});
app.post('/api/categorias',async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({erro:'Informe o nome da categoria.'});const [dup]=await pool.query('SELECT id FROM categorias WHERE LOWER(nome)=LOWER(?)',[name]);if(dup.length)return res.status(409).json({erro:'Já existe uma categoria com esse nome.'});const [r]=await pool.query('INSERT INTO categorias (nome,descricao,ativo) VALUES (?,?,1)',[name,req.body.description||null]);const [rows]=await pool.query('SELECT id,nome AS name,descricao AS description,ativo,criado_em AS createdAt FROM categorias WHERE id=?',[r.insertId]);res.status(201).json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.put('/api/categorias/:id',async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({erro:'Informe o nome da categoria.'});const [dup]=await pool.query('SELECT id FROM categorias WHERE LOWER(nome)=LOWER(?) AND id<>?',[name,req.params.id]);if(dup.length)return res.status(409).json({erro:'Já existe outra categoria com esse nome.'});const [r]=await pool.query('UPDATE categorias SET nome=?,descricao=? WHERE id=?',[name,req.body.description||null,req.params.id]);if(!r.affectedRows)return res.status(404).json({erro:'Categoria não encontrada.'});const [rows]=await pool.query('SELECT id,nome AS name,descricao AS description,ativo,criado_em AS createdAt FROM categorias WHERE id=?',[req.params.id]);res.json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.delete('/api/categorias/:id',async(req,res)=>{try{const [p]=await pool.query('SELECT COUNT(*) AS total FROM produtos WHERE categoria_id=?',[req.params.id]);if(Number(p[0].total)>0)return res.status(409).json({erro:'Não é possível excluir uma categoria utilizada por produtos.'});const [r]=await pool.query('DELETE FROM categorias WHERE id=?',[req.params.id]);if(!r.affectedRows)return res.status(404).json({erro:'Categoria não encontrada.'});res.json({sucesso:true})}catch(e){res.status(500).json({erro:e.message})}});

app.get('/api/fornecedores',async(req,res)=>{try{const [rows]=await pool.query(`SELECT id,nome AS name,cnpj AS document,email,telefone AS phone,contato AS contact,endereco AS address,cidade AS city,estado AS state,observacao AS notes,ativo AS active,criado_em AS createdAt FROM fornecedores ORDER BY nome`);res.json(rows)}catch(e){res.status(500).json({erro:e.message})}});
app.post('/api/fornecedores',async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({erro:'Informe o nome do fornecedor.'});const [dup]=await pool.query('SELECT id FROM fornecedores WHERE LOWER(nome)=LOWER(?)',[name]);if(dup.length)return res.status(409).json({erro:'Já existe um fornecedor com esse nome.'});const [r]=await pool.query('INSERT INTO fornecedores (nome,cnpj,email,telefone,contato,endereco,cidade,estado,observacao,ativo) VALUES (?,?,?,?,?,?,?,?,?,?)',[name,req.body.document||null,req.body.email||null,req.body.phone||null,req.body.contact||null,req.body.address||null,req.body.city||null,req.body.state||null,req.body.notes||null,req.body.active===false?0:1]);const [rows]=await pool.query('SELECT id,nome AS name,cnpj AS document,email,telefone AS phone,contato AS contact,endereco AS address,cidade AS city,estado AS state,observacao AS notes,ativo AS active,criado_em AS createdAt FROM fornecedores WHERE id=?',[r.insertId]);res.status(201).json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.put('/api/fornecedores/:id',async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({erro:'Informe o nome do fornecedor.'});const [dup]=await pool.query('SELECT id FROM fornecedores WHERE LOWER(nome)=LOWER(?) AND id<>?',[name,req.params.id]);if(dup.length)return res.status(409).json({erro:'Já existe outro fornecedor com esse nome.'});const [r]=await pool.query('UPDATE fornecedores SET nome=?,cnpj=?,email=?,telefone=?,contato=?,endereco=?,cidade=?,estado=?,observacao=?,ativo=? WHERE id=?',[name,req.body.document||null,req.body.email||null,req.body.phone||null,req.body.contact||null,req.body.address||null,req.body.city||null,req.body.state||null,req.body.notes||null,req.body.active===false?0:1,req.params.id]);if(!r.affectedRows)return res.status(404).json({erro:'Fornecedor não encontrado.'});const [rows]=await pool.query('SELECT id,nome AS name,cnpj AS document,email,telefone AS phone,contato AS contact,endereco AS address,cidade AS city,estado AS state,observacao AS notes,ativo AS active,criado_em AS createdAt FROM fornecedores WHERE id=?',[req.params.id]);res.json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.delete('/api/fornecedores/:id',async(req,res)=>{try{const [p]=await pool.query('SELECT COUNT(*) AS total FROM produtos WHERE fornecedor_id=?',[req.params.id]);if(Number(p[0].total)>0)return res.status(409).json({erro:'Não é possível excluir um fornecedor utilizado por produtos.'});const [r]=await pool.query('DELETE FROM fornecedores WHERE id=?',[req.params.id]);if(!r.affectedRows)return res.status(404).json({erro:'Fornecedor não encontrado.'});res.json({sucesso:true})}catch(e){res.status(500).json({erro:e.message})}});

app.post('/api/auth/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const password=String(req.body.password||'');const [rows]=await pool.query('SELECT id,nome AS name,email,senha AS password,role,ativo AS active,criado_em AS createdAt FROM usuarios WHERE LOWER(email)=LOWER(?) LIMIT 1',[email]);const user=rows[0];if(!user||String(user.password)!==password)return res.status(401).json({erro:'E-mail ou senha inválidos.'});if(!user.active)return res.status(403).json({erro:'Este usuário está inativo.'});delete user.password;res.json(user)}catch(e){res.status(500).json({erro:e.message})}});
app.get('/api/usuarios',async(req,res)=>{try{const [rows]=await pool.query('SELECT id,nome AS name,email,role,ativo AS active,criado_em AS createdAt FROM usuarios ORDER BY nome');res.json(rows)}catch(e){res.status(500).json({erro:e.message})}});
app.post('/api/usuarios',async(req,res)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name)return res.status(400).json({erro:'Informe o nome do usuário.'});if(!email.includes('@'))return res.status(400).json({erro:'Informe um e-mail válido.'});if(password.length<4)return res.status(400).json({erro:'A senha deve ter pelo menos 4 caracteres.'});const [dup]=await pool.query('SELECT id FROM usuarios WHERE LOWER(email)=LOWER(?)',[email]);if(dup.length)return res.status(409).json({erro:'Já existe um usuário com esse e-mail.'});const [r]=await pool.query('INSERT INTO usuarios (nome,email,senha,role,ativo) VALUES (?,?,?,?,?)',[name,email,password,req.body.role||'FUNCIONARIO',req.body.active===false?0:1]);const [rows]=await pool.query('SELECT id,nome AS name,email,role,ativo AS active,criado_em AS createdAt FROM usuarios WHERE id=?',[r.insertId]);res.status(201).json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.put('/api/usuarios/:id',async(req,res)=>{try{const [curRows]=await pool.query('SELECT id,nome AS name,email,senha AS password,role,ativo AS active,criado_em AS createdAt FROM usuarios WHERE id=?',[req.params.id]);if(!curRows.length)return res.status(404).json({erro:'Usuário não encontrado.'});const cur=curRows[0];const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase();if(!name||!email.includes('@'))return res.status(400).json({erro:'Nome e e-mail são obrigatórios.'});if(email!==cur.email){const [dup]=await pool.query('SELECT id FROM usuarios WHERE LOWER(email)=LOWER(?) AND id<>?',[email,req.params.id]);if(dup.length)return res.status(409).json({erro:'Já existe outro usuário com esse e-mail.'})}const nextRole=req.body.role||cur.role,nextActive=req.body.active!==false; if(cur.role==='ADMIN'&&cur.active&&!(nextRole==='ADMIN'&&nextActive)){const [a]=await pool.query("SELECT COUNT(*) AS total FROM usuarios WHERE role='ADMIN' AND ativo=1 AND id<>?",[req.params.id]);if(Number(a[0].total)===0)return res.status(409).json({erro:'Não é possível remover ou inativar o último administrador ativo.'})}const password=req.body.password?String(req.body.password):cur.password;if(req.body.password!==undefined&&req.body.password!==''&&password.length<4)return res.status(400).json({erro:'A senha deve ter pelo menos 4 caracteres.'});await pool.query('UPDATE usuarios SET nome=?,email=?,senha=?,role=?,ativo=? WHERE id=?',[name,email,password,nextRole,nextActive?1:0,req.params.id]);const [rows]=await pool.query('SELECT id,nome AS name,email,role,ativo AS active,criado_em AS createdAt FROM usuarios WHERE id=?',[req.params.id]);res.json(rows[0])}catch(e){res.status(500).json({erro:e.message})}});
app.delete('/api/usuarios/:id',async(req,res)=>{try{const [u]=await pool.query('SELECT role,ativo FROM usuarios WHERE id=?',[req.params.id]);if(!u.length)return res.status(404).json({erro:'Usuário não encontrado.'});if(u[0].role==='ADMIN'&&u[0].ativo){const [a]=await pool.query("SELECT COUNT(*) AS total FROM usuarios WHERE role='ADMIN' AND ativo=1");if(Number(a[0].total)<=1)return res.status(409).json({erro:'Não é possível excluir o último administrador ativo.'})}await pool.query('DELETE FROM usuarios WHERE id=?',[req.params.id]);res.json({sucesso:true})}catch(e){res.status(500).json({erro:e.message})}});

app.get('/api/movimentacoes',async(req,res)=>{try{const type=req.query.type;let sql=`SELECT m.id,m.tipo AS type,m.produto_id AS productId,p.nome AS productName,p.sku AS productSku,p.unidade AS unit,m.quantidade AS quantity,m.estoque_anterior AS previousStock,m.estoque_posterior AS newStock,m.fornecedor_id AS supplierId,COALESCE(f.nome,'') AS supplierName,m.documento AS document,m.motivo AS reason,m.destino AS destination,m.observacao AS notes,COALESCE(m.data_movimentacao,DATE(m.criado_em)) AS movementDate,m.criado_em AS createdAt,COALESCE(u.nome,'Administrador') AS userName FROM movimentacoes m JOIN produtos p ON p.id=m.produto_id LEFT JOIN fornecedores f ON f.id=m.fornecedor_id LEFT JOIN usuarios u ON u.id=m.usuario_id`;const params=[];if(type){sql+=' WHERE m.tipo=?';params.push(type)}sql+=' ORDER BY m.criado_em DESC,m.id DESC';const [rows]=await pool.query(sql,params);res.json(rows)}catch(e){res.status(500).json({erro:e.message,detalhes:e.message})}});

async function createMovement(req,res,type){const c=await pool.getConnection();try{const d=req.body, productId=Number(d.productId??d.produto_id), qty=Number(d.quantity??d.quantidade);if(!productId)return res.status(400).json({erro:'Selecione um produto.'});if(!Number.isFinite(qty)||qty<=0)return res.status(400).json({erro:'Informe uma quantidade maior que zero.'});if(type==='SAIDA'&&!String(d.reason||'').trim())return res.status(400).json({erro:'Informe o motivo da saída.'});await c.beginTransaction();const [ps]=await c.query('SELECT id,estoque FROM produtos WHERE id=? FOR UPDATE',[productId]);if(!ps.length)throw new Error('Produto não encontrado.');const prev=Number(ps[0].estoque||0);if(type==='SAIDA'&&qty>prev)throw new Error(`Estoque insuficiente. Existem apenas ${prev} unidades disponíveis.`);const next=type==='ENTRADA'?prev+qty:prev-qty;await c.query('UPDATE produtos SET estoque=? WHERE id=?',[next,productId]);const [r]=await c.query(`INSERT INTO movimentacoes (produto_id,usuario_id,tipo,quantidade,estoque_anterior,estoque_posterior,fornecedor_id,documento,motivo,destino,observacao,data_movimentacao) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[productId,d.usuario_id||1,type,qty,prev,next,d.supplierId||null,d.document||null,d.reason||null,d.destination||null,d.notes||null,d.movementDate||null]);await c.commit();const [rows]=await pool.query(`SELECT m.id,m.tipo AS type,m.produto_id AS productId,p.nome AS productName,p.sku AS productSku,p.unidade AS unit,m.quantidade AS quantity,m.estoque_anterior AS previousStock,m.estoque_posterior AS newStock,m.fornecedor_id AS supplierId,COALESCE(f.nome,'') AS supplierName,m.documento AS document,m.motivo AS reason,m.destino AS destination,m.observacao AS notes,COALESCE(m.data_movimentacao,DATE(m.criado_em)) AS movementDate,m.criado_em AS createdAt,COALESCE(u.nome,'Administrador') AS userName FROM movimentacoes m JOIN produtos p ON p.id=m.produto_id LEFT JOIN fornecedores f ON f.id=m.fornecedor_id LEFT JOIN usuarios u ON u.id=m.usuario_id WHERE m.id=?`,[r.insertId]);res.status(201).json(rows[0])}catch(e){await c.rollback();res.status(400).json({erro:e.message})}finally{c.release()}}
app.post('/api/movimentacoes/entrada',(req,res)=>createMovement(req,res,'ENTRADA'));
app.post('/api/movimentacoes/saida',(req,res)=>createMovement(req,res,'SAIDA'));

async function start(){try{await pool.query('SELECT 1');await ensureSchema();const [p]=await pool.query('SELECT COUNT(*) AS total FROM produtos');console.log(`📦 Produtos no banco: ${p[0].total}`);console.log('🗄️ Banco pronto.');const PORT=process.env.PORT||3001;app.listen(PORT,()=>console.log(`🚀 API rodando em http://localhost:${PORT}`))}catch(e){console.error('❌ Falha ao iniciar API:',e);process.exit(1)}}
start();
